// <auto-generated />
using System;
using CoreApiDirect.Demo.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CoreApiDirect.Demo.Migrations.LogDb
{
    [DbContext(typeof(LogDbContext))]
    partial class LogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.Logging.LogDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LogDate");

                    b.Property<int>("LogEventId");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("LogEventId")
                        .IsUnique();

                    b.ToTable("LogDetail");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.Logging.LogEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.ToTable("LogEvents");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.Logging.SystemInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("LogEventId");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("OSVersion")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("LogEventId")
                        .IsUnique();

                    b.ToTable("SystemInfo");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.Logging.LogDetail", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.Logging.LogEvent", "LogEvent")
                        .WithOne("LogDetail")
                        .HasForeignKey("CoreApiDirect.Demo.Entities.Logging.LogDetail", "LogEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.Logging.SystemInfo", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.Logging.LogEvent", "LogEvent")
                        .WithOne("SystemInfo")
                        .HasForeignKey("CoreApiDirect.Demo.Entities.Logging.SystemInfo", "LogEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
