// <auto-generated />
using System;
using CoreApiDirect.Demo.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CoreApiDirect.Demo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LessonId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(255);

                    b.Property<string>("Email")
                        .HasMaxLength(255);

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.ToTable("ContactInfo");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Lesson", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("SchoolId");

                    b.Property<int>("WeekHours");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ContactInfoId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("ContactInfoId");

                    b.ToTable("Phones");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int?>("YearOfEstablishment");

                    b.HasKey("Id");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SchoolId");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.StudentLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LessonId");

                    b.Property<int>("StudentId");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentLessons");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Book", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.App.Lesson", "Lesson")
                        .WithMany("Books")
                        .HasForeignKey("LessonId");
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.ContactInfo", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.App.Student", "Student")
                        .WithOne("ContactInfo")
                        .HasForeignKey("CoreApiDirect.Demo.Entities.App.ContactInfo", "StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Lesson", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.App.School", "School")
                        .WithMany("Lessons")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Phone", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.App.ContactInfo", "ContactInfo")
                        .WithMany("Phones")
                        .HasForeignKey("ContactInfoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.Student", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.App.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CoreApiDirect.Demo.Entities.App.StudentLesson", b =>
                {
                    b.HasOne("CoreApiDirect.Demo.Entities.App.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("CoreApiDirect.Demo.Entities.App.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
