using System;
using System.Collections.Generic;
using CoreApiDirect.Demo.Entities.App;
using CoreApiDirect.Demo.Entities.Logging;

namespace CoreApiDirect.Demo.DataContext
{
    internal class InitialData
    {
        public const string LESSON01_ID = "5E97380B-E5D3-48D3-91B3-55AF99C9B5C2";
        public const string LESSON02_ID = "1E75BB67-4F33-4B26-9DB8-92E826243389";
        public const string LESSON03_ID = "064439D5-7FD9-4E49-8129-3553842F00B2";
        public const string LESSON04_ID = "742D0463-343B-47B7-B794-B7618F232237";
        public const string LESSON05_ID = "B7DFC49D-5247-4EC4-B80B-F527C209A3F4";
        public const string LESSON06_ID = "1CB0E60F-51E0-46B4-BD2E-D9A0AC0E13CD";
        public const string LESSON07_ID = "0F8EC3DB-4AB3-4E3C-B703-7C75F19C4EA6";
        public const string LESSON08_ID = "B5E4B46F-E171-4F22-823F-EC20E2C47FB4";
        public const string LESSON09_ID = "80172BD7-FE0F-426A-85F7-AA14E38F4B1A";
        public const string LESSON10_ID = "711F7F1C-1C6E-48A4-B036-36961329B021";
        public const string LESSON11_ID = "535043A4-74D5-4824-AC69-83286B51F81F";
        public const string LESSON12_ID = "4EED6C8F-DEE7-4FBF-8099-405CBC430C53";
        public const string LESSON13_ID = "A2903BD7-B950-4401-9B3A-D8A3861640C7";
        public const string LESSON14_ID = "4093A005-129B-4CC0-9E34-92572F43076B";
        public const string LESSON15_ID = "506EF1C5-E0AB-42F5-8AF6-8FBB9E40D813";
        public const string LESSON16_ID = "177A99D8-78B0-474D-8C32-B8882CEB350C";
        public const string LESSON17_ID = "F4DB4E8B-D4FC-4D85-A3E6-950B41EF307A";
        public const string LESSON18_ID = "112E0034-8C15-4E21-9806-2B8E925D88A0";
        public const string LESSON19_ID = "506CABDB-4C50-4002-8577-A2160548BAB6";
        public const string LESSON20_ID = "16C91B76-2EAA-4806-9982-132AFB1385D9";

        public List<Book> Books { get; set; } = new List<Book>();
        public List<ContactInfo> ContactInfo { get; set; } = new List<ContactInfo>();
        public List<Lesson> Lessons { get; set; } = new List<Lesson>();
        public List<Phone> Phones { get; set; } = new List<Phone>();
        public List<School> Schools { get; set; } = new List<School>();
        public List<Student> Students { get; set; } = new List<Student>();
        public List<StudentLesson> StudentLessons { get; set; } = new List<StudentLesson>();
        public List<LogEvent> LogEvents { get; set; } = new List<LogEvent>();
        public List<LogDetail> LogDetail { get; set; } = new List<LogDetail>();
        public List<SystemInfo> SystemInfo { get; set; } = new List<SystemInfo>();

        public InitialData()
        {
            var school1 = new School { Name = "University of Pennsylvania", YearOfEstablishment = 1740 };
            var school2 = new School { Name = "University of Minnesota", YearOfEstablishment = 1851 };
            var school3 = new School { Name = "Massachusetts Institute of Technology", YearOfEstablishment = 1861 };
            var school4 = new School { Name = "University of Washington" };
            var school5 = new School { Name = "Stanford University", YearOfEstablishment = 1891 };

            Schools.Add(school1);
            Schools.Add(school2);
            Schools.Add(school3);
            Schools.Add(school4);
            Schools.Add(school5);

            var lesson01 = new Lesson { Id = LESSON01_ID, Name = "Chemistry", WeekHours = 4, School = school1 };
            var lesson02 = new Lesson { Id = LESSON02_ID, Name = "Ancient greek", WeekHours = 6, School = school1 };
            var lesson03 = new Lesson { Id = LESSON03_ID, Name = "Agriculture", WeekHours = 3, School = school1 };
            var lesson04 = new Lesson { Id = LESSON04_ID, Name = "Finance", WeekHours = 3, School = school1 };
            var lesson05 = new Lesson { Id = LESSON05_ID, Name = "Mathematics", WeekHours = 5, School = school2 };
            var lesson06 = new Lesson { Id = LESSON06_ID, Name = "Philosophy", WeekHours = 5, School = school2 };
            var lesson07 = new Lesson { Id = LESSON07_ID, Name = "English", WeekHours = 4, School = school2 };
            var lesson08 = new Lesson { Id = LESSON08_ID, Name = "Biology", WeekHours = 4, School = school2 };
            var lesson09 = new Lesson { Id = LESSON09_ID, Name = "Algorithms", WeekHours = 4, School = school3 };
            var lesson10 = new Lesson { Id = LESSON10_ID, Name = "Programming", WeekHours = 6, School = school3 };
            var lesson11 = new Lesson { Id = LESSON11_ID, Name = "Networks", WeekHours = 6, School = school3 };
            var lesson12 = new Lesson { Id = LESSON12_ID, Name = "Analysis", WeekHours = 2, School = school3 };
            var lesson13 = new Lesson { Id = LESSON13_ID, Name = "Poetry", WeekHours = 8, School = school4 };
            var lesson14 = new Lesson { Id = LESSON14_ID, Name = "Algebra", WeekHours = 8, School = school4 };
            var lesson15 = new Lesson { Id = LESSON15_ID, Name = "Physics", WeekHours = 4, School = school4 };
            var lesson16 = new Lesson { Id = LESSON16_ID, Name = "Politics", WeekHours = 6, School = school4 };
            var lesson17 = new Lesson { Id = LESSON17_ID, Name = "Literature", WeekHours = 2, School = school5 };
            var lesson18 = new Lesson { Id = LESSON18_ID, Name = "Computers", WeekHours = 1, School = school5 };
            var lesson19 = new Lesson { Id = LESSON19_ID, Name = "History", WeekHours = 4, School = school5 };
            var lesson20 = new Lesson { Id = LESSON20_ID, Name = "Sociology", WeekHours = 4, School = school5 };

            Lessons.Add(lesson01);
            Lessons.Add(lesson02);
            Lessons.Add(lesson03);
            Lessons.Add(lesson04);
            Lessons.Add(lesson05);
            Lessons.Add(lesson06);
            Lessons.Add(lesson07);
            Lessons.Add(lesson08);
            Lessons.Add(lesson09);
            Lessons.Add(lesson10);
            Lessons.Add(lesson11);
            Lessons.Add(lesson12);
            Lessons.Add(lesson13);
            Lessons.Add(lesson14);
            Lessons.Add(lesson15);
            Lessons.Add(lesson16);
            Lessons.Add(lesson17);
            Lessons.Add(lesson18);
            Lessons.Add(lesson19);
            Lessons.Add(lesson20);

            Books.Add(new Book { Name = "Organic chemistry", Lesson = lesson01 });
            Books.Add(new Book { Name = "The Odyssey", Lesson = lesson02 });
            Books.Add(new Book { Name = "Anabasis", Lesson = lesson02 });
            Books.Add(new Book { Name = "You can farm", Lesson = lesson03 });
            Books.Add(new Book { Name = "The intelligent investor", Lesson = lesson04 });
            Books.Add(new Book { Name = "Personal finance", Lesson = lesson04 });
            Books.Add(new Book { Name = "The mathematical experience", Lesson = lesson05 });
            Books.Add(new Book { Name = "The philosophy in 15th century", Lesson = lesson06 });
            Books.Add(new Book { Name = "Great philosophers", Lesson = lesson06 });
            Books.Add(new Book { Name = "English vocabulary", Lesson = lesson07 });
            Books.Add(new Book { Name = "Our body", Lesson = lesson08 });
            Books.Add(new Book { Name = "Evolution of species", Lesson = lesson08 });
            Books.Add(new Book { Name = "The algorithm design manual", Lesson = lesson09 });
            Books.Add(new Book { Name = "Code complete", Lesson = lesson10 });
            Books.Add(new Book { Name = "The art of computer programming", Lesson = lesson10 });
            Books.Add(new Book { Name = "Computer networks", Lesson = lesson11 });
            Books.Add(new Book { Name = "Understanding analysis", Lesson = lesson12 });
            Books.Add(new Book { Name = "The way of analysis", Lesson = lesson12 });
            Books.Add(new Book { Name = "The book of poerty", Lesson = lesson13 });
            Books.Add(new Book { Name = "Algebra today", Lesson = lesson14 });
            Books.Add(new Book { Name = "The algebra way", Lesson = lesson14 });
            Books.Add(new Book { Name = "Physics in the lab", Lesson = lesson15 });
            Books.Add(new Book { Name = "True or lie", Lesson = lesson16 });
            Books.Add(new Book { Name = "Being a politician", Lesson = lesson16 });
            Books.Add(new Book { Name = "Animal farm", Lesson = lesson17 });
            Books.Add(new Book { Name = "Press enter to continue", Lesson = lesson18 });
            Books.Add(new Book { Name = "From zero to one", Lesson = lesson18 });
            Books.Add(new Book { Name = "The great wars", Lesson = lesson19 });
            Books.Add(new Book { Name = "The human nature", Lesson = lesson20 });
            Books.Add(new Book { Name = "The myth of equality", Lesson = lesson20 });

            var student01 = new Student { FirstName = "Mark", LastName = "Smith", DateOfBirth = new DateTime(2000, 6, 12), School = school1 };
            var student02 = new Student { FirstName = "Mary", LastName = "Johnson", DateOfBirth = new DateTime(1998, 4, 22), School = school1 };
            var student03 = new Student { FirstName = "John", LastName = "Jones", DateOfBirth = new DateTime(1999, 1, 1), School = school1 };
            var student04 = new Student { FirstName = "Patricia", LastName = "Brown", DateOfBirth = new DateTime(1995, 3, 4), School = school1 };
            var student05 = new Student { FirstName = "Mark", LastName = "Davis", DateOfBirth = new DateTime(1997, 5, 12), School = school1 };
            var student06 = new Student { FirstName = "Linda", LastName = "Miller", DateOfBirth = new DateTime(2001, 11, 23), School = school1 };
            var student07 = new Student { FirstName = "Michael", LastName = "Wilson", DateOfBirth = new DateTime(2001, 2, 8), School = school1 };
            var student08 = new Student { FirstName = "Barbara", LastName = "Moore", DateOfBirth = new DateTime(2000, 12, 22), School = school1 };
            var student09 = new Student { FirstName = "Mark", LastName = "Taylor", DateOfBirth = new DateTime(1999, 2, 13), School = school1 };
            var student10 = new Student { FirstName = "Elizabeth", LastName = "Anderson", DateOfBirth = new DateTime(2000, 1, 10), School = school1 };
            var student11 = new Student { FirstName = "David", LastName = "Thomas", DateOfBirth = new DateTime(1996, 6, 7), School = school1 };
            var student12 = new Student { FirstName = "Jennifer", LastName = "Jackson", DateOfBirth = new DateTime(1997, 8, 1), School = school1 };
            var student13 = new Student { FirstName = "Mark", LastName = "White", DateOfBirth = new DateTime(1997, 5, 20), School = school1 };
            var student14 = new Student { FirstName = "Susan", LastName = "Harris", DateOfBirth = new DateTime(1996, 4, 23), School = school1 };
            var student15 = new Student { FirstName = "Charles", LastName = "Martin", DateOfBirth = new DateTime(1995, 9, 3), School = school1 };
            var student16 = new Student { FirstName = "Dorothy", LastName = "Thompson", DateOfBirth = new DateTime(2000, 2, 5), School = school1 };
            var student17 = new Student { FirstName = "Joseph", LastName = "Robinson", DateOfBirth = new DateTime(2001, 6, 7), School = school2 };
            var student18 = new Student { FirstName = "Lisa", LastName = "Clark", DateOfBirth = new DateTime(1999, 11, 11), School = school2 };
            var student19 = new Student { FirstName = "Thomas", LastName = "Lewis", DateOfBirth = new DateTime(1998, 10, 3), School = school2 };
            var student20 = new Student { FirstName = "Nancy", LastName = "Lee", DateOfBirth = new DateTime(1997, 1, 23), School = school2 };
            var student21 = new Student { FirstName = "Christopher", LastName = "Walker", DateOfBirth = new DateTime(1996, 2, 21), School = school2 };
            var student22 = new Student { FirstName = "Karen", LastName = "Hall", DateOfBirth = new DateTime(1999, 8, 2), School = school2 };
            var student23 = new Student { FirstName = "Daniel", LastName = "Allen", DateOfBirth = new DateTime(1998, 4, 12), School = school2 };
            var student24 = new Student { FirstName = "Betty", LastName = "Young", DateOfBirth = new DateTime(2000, 6, 26), School = school2 };
            var student25 = new Student { FirstName = "Paul", LastName = "King", DateOfBirth = new DateTime(1999, 7, 12), School = school2 };
            var student26 = new Student { FirstName = "Helen", LastName = "Wright", DateOfBirth = new DateTime(2000, 3, 22), School = school2 };
            var student27 = new Student { FirstName = "James", LastName = "Hill", DateOfBirth = new DateTime(1995, 4, 1), School = school2 };
            var student28 = new Student { FirstName = "Sandra", LastName = "Scott", DateOfBirth = new DateTime(1999, 9, 12), School = school2 };
            var student29 = new Student { FirstName = "Donald", LastName = "Green", DateOfBirth = new DateTime(1998, 12, 30), School = school2 };
            var student30 = new Student { FirstName = "Donna", LastName = "Adams", DateOfBirth = new DateTime(1998, 7, 13), School = school2 };
            var student31 = new Student { FirstName = "Roy", LastName = "Carter", DateOfBirth = new DateTime(1996, 5, 5), School = school2 };
            var student32 = new Student { FirstName = "Pamela", LastName = "Parker", DateOfBirth = new DateTime(1997, 10, 8), School = school2 };
            var student33 = new Student { FirstName = "Thomas", LastName = "Jackson", DateOfBirth = new DateTime(1998, 1, 8), School = school3 };
            var student34 = new Student { FirstName = "Donna", LastName = "Lewis", DateOfBirth = new DateTime(1999, 1, 5), School = school3 };
            var student35 = new Student { FirstName = "David", LastName = "Lewis", DateOfBirth = new DateTime(1999, 10, 12), School = school3 };
            var student36 = new Student { FirstName = "Dorothy", LastName = "Hill", DateOfBirth = new DateTime(1997, 11, 12), School = school3 };
            var student37 = new Student { FirstName = "Donald", LastName = "Jones", DateOfBirth = new DateTime(2000, 12, 23), School = school3 };
            var student38 = new Student { FirstName = "Betty", LastName = "Allen", DateOfBirth = new DateTime(1996, 6, 29), School = school3 };
            var student39 = new Student { FirstName = "James", LastName = "Carter", DateOfBirth = new DateTime(1996, 7, 30), School = school3 };
            var student40 = new Student { FirstName = "Linda", LastName = "Robinson", DateOfBirth = new DateTime(1998, 11, 4), School = school3 };
            var student41 = new Student { FirstName = "Michael", LastName = "Smith", DateOfBirth = new DateTime(1997, 3, 10), School = school3 };
            var student42 = new Student { FirstName = "Sandra", LastName = "Walker", DateOfBirth = new DateTime(1997, 4, 7), School = school3 };
            var student43 = new Student { FirstName = "Daniel", LastName = "Adams", DateOfBirth = new DateTime(1997, 4, 12), School = school3 };
            var student44 = new Student { FirstName = "Helen", LastName = "Smith", DateOfBirth = new DateTime(1995, 5, 27), School = school3 };
            var student45 = new Student { FirstName = "Daniel", LastName = "Martin", DateOfBirth = new DateTime(1999, 12, 23), School = school3 };
            var student46 = new Student { FirstName = "Mary", LastName = "King", DateOfBirth = new DateTime(1996, 9, 24), School = school3 };
            var student47 = new Student { FirstName = "Paul", LastName = "Walker", DateOfBirth = new DateTime(1999, 9, 4), School = school3 };
            var student48 = new Student { FirstName = "Mary", LastName = "Lee", DateOfBirth = new DateTime(2000, 10, 7), School = school3 };
            var student49 = new Student { FirstName = "Joseph", LastName = "Hill", DateOfBirth = new DateTime(1998, 1, 22), School = school4 };
            var student50 = new Student { FirstName = "Barbara", LastName = "Lewis", DateOfBirth = new DateTime(2000, 7, 30), School = school4 };
            var student51 = new Student { FirstName = "James", LastName = "Lee", DateOfBirth = new DateTime(2001, 7, 3), School = school4 };
            var student52 = new Student { FirstName = "Mary", LastName = "Adams", DateOfBirth = new DateTime(1996, 5, 4), School = school4 };
            var student53 = new Student { FirstName = "David", LastName = "Hall", DateOfBirth = new DateTime(1997, 9, 11), School = school4 };
            var student54 = new Student { FirstName = "Lisa", LastName = "Jones", DateOfBirth = new DateTime(1998, 8, 18), School = school4 };
            var student55 = new Student { FirstName = "Charles", LastName = "Allen", DateOfBirth = new DateTime(1999, 11, 17), School = school4 };
            var student56 = new Student { FirstName = "Helen", LastName = "Wilson", DateOfBirth = new DateTime(1995, 11, 7), School = school4 };
            var student57 = new Student { FirstName = "Donald", LastName = "Miller", DateOfBirth = new DateTime(2001, 12, 6), School = school4 };
            var student58 = new Student { FirstName = "Dorothy", LastName = "Davis", DateOfBirth = new DateTime(2000, 1, 10), School = school4 };
            var student59 = new Student { FirstName = "Roy", LastName = "Brown", DateOfBirth = new DateTime(1998, 2, 27), School = school4 };
            var student60 = new Student { FirstName = "Patricia", LastName = "Clark", DateOfBirth = new DateTime(1998, 5, 31), School = school4 };
            var student61 = new Student { FirstName = "Daniel", LastName = "Lewis", DateOfBirth = new DateTime(1997, 10, 3), School = school4 };
            var student62 = new Student { FirstName = "Karen", LastName = "Johnson", DateOfBirth = new DateTime(1997, 8, 22), School = school4 };
            var student63 = new Student { FirstName = "John", LastName = "Smith", DateOfBirth = new DateTime(2000, 8, 1), School = school4 };
            var student64 = new Student { FirstName = "Mary", LastName = "Green", DateOfBirth = new DateTime(1999, 3, 9), School = school4 };
            var student65 = new Student { FirstName = "Mark", LastName = "Scott", DateOfBirth = new DateTime(1998, 6, 8), School = school5 };
            var student66 = new Student { FirstName = "Sandra", LastName = "King", DateOfBirth = new DateTime(1997, 9, 7), School = school5 };
            var student67 = new Student { FirstName = "Donald", LastName = "Smith", DateOfBirth = new DateTime(2000, 11, 19), School = school5 };
            var student68 = new Student { FirstName = "Betty", LastName = "Smith", DateOfBirth = new DateTime(2001, 2, 9), School = school5 };
            var student69 = new Student { FirstName = "Michael", LastName = "Lee", DateOfBirth = new DateTime(2001, 10, 29), School = school5 };
            var student70 = new Student { FirstName = "Patricia", LastName = "Wood", DateOfBirth = new DateTime(2000, 11, 10), School = school5 };
            var student71 = new Student { FirstName = "Joseph", LastName = "Wright", DateOfBirth = new DateTime(2000, 12, 9), School = school5 };
            var student72 = new Student { FirstName = "Dorothy", LastName = "Carter", DateOfBirth = new DateTime(1998, 9, 2), School = school5 };
            var student73 = new Student { FirstName = "John", LastName = "Parker", DateOfBirth = new DateTime(1998, 1, 4), School = school5 };
            var student74 = new Student { FirstName = "Donna", LastName = "Harris", DateOfBirth = new DateTime(1997, 2, 7), School = school5 };
            var student75 = new Student { FirstName = "James", LastName = "Moore", DateOfBirth = new DateTime(1996, 4, 14), School = school5 };
            var student76 = new Student { FirstName = "Susan", LastName = "Allen", DateOfBirth = new DateTime(1998, 6, 28), School = school5 };
            var student77 = new Student { FirstName = "Charles", LastName = "Jackson", DateOfBirth = new DateTime(1995, 11, 30), School = school5 };
            var student78 = new Student { FirstName = "Susan", LastName = "Robinson", DateOfBirth = new DateTime(2000, 12, 31), School = school5 };
            var student79 = new Student { FirstName = "Michael", LastName = "Scott", DateOfBirth = new DateTime(1999, 8, 5), School = school5 };
            var student80 = new Student { FirstName = "Lisa", LastName = "Hall", DateOfBirth = new DateTime(1999, 6, 5), School = school5 };

            Students.Add(student01);
            Students.Add(student02);
            Students.Add(student03);
            Students.Add(student04);
            Students.Add(student05);
            Students.Add(student06);
            Students.Add(student07);
            Students.Add(student08);
            Students.Add(student09);
            Students.Add(student10);
            Students.Add(student11);
            Students.Add(student12);
            Students.Add(student13);
            Students.Add(student14);
            Students.Add(student15);
            Students.Add(student16);
            Students.Add(student17);
            Students.Add(student18);
            Students.Add(student19);
            Students.Add(student20);
            Students.Add(student21);
            Students.Add(student22);
            Students.Add(student23);
            Students.Add(student24);
            Students.Add(student25);
            Students.Add(student26);
            Students.Add(student27);
            Students.Add(student28);
            Students.Add(student29);
            Students.Add(student30);
            Students.Add(student31);
            Students.Add(student32);
            Students.Add(student33);
            Students.Add(student34);
            Students.Add(student35);
            Students.Add(student36);
            Students.Add(student37);
            Students.Add(student38);
            Students.Add(student39);
            Students.Add(student40);
            Students.Add(student41);
            Students.Add(student42);
            Students.Add(student43);
            Students.Add(student44);
            Students.Add(student45);
            Students.Add(student46);
            Students.Add(student47);
            Students.Add(student48);
            Students.Add(student49);
            Students.Add(student50);
            Students.Add(student51);
            Students.Add(student52);
            Students.Add(student53);
            Students.Add(student54);
            Students.Add(student55);
            Students.Add(student56);
            Students.Add(student57);
            Students.Add(student58);
            Students.Add(student59);
            Students.Add(student60);
            Students.Add(student61);
            Students.Add(student62);
            Students.Add(student63);
            Students.Add(student64);
            Students.Add(student65);
            Students.Add(student66);
            Students.Add(student67);
            Students.Add(student68);
            Students.Add(student69);
            Students.Add(student70);
            Students.Add(student71);
            Students.Add(student72);
            Students.Add(student73);
            Students.Add(student74);
            Students.Add(student75);
            Students.Add(student76);
            Students.Add(student77);
            Students.Add(student78);
            Students.Add(student79);
            Students.Add(student80);

            StudentLessons.Add(new StudentLesson { Student = student01, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student01, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student02, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student02, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student03, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student03, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student04, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student04, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student05, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student05, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student06, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student06, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student07, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student07, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student08, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student08, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student09, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student09, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student10, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student10, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student11, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student11, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student12, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student12, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student13, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student13, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student14, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student14, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student15, Lesson = lesson01 });
            StudentLessons.Add(new StudentLesson { Student = student15, Lesson = lesson02 });
            StudentLessons.Add(new StudentLesson { Student = student16, Lesson = lesson03 });
            StudentLessons.Add(new StudentLesson { Student = student16, Lesson = lesson04 });
            StudentLessons.Add(new StudentLesson { Student = student17, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student17, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student18, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student18, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student19, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student19, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student20, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student20, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student21, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student21, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student22, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student22, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student23, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student23, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student24, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student24, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student25, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student25, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student26, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student26, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student27, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student27, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student28, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student28, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student29, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student29, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student30, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student30, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student31, Lesson = lesson05 });
            StudentLessons.Add(new StudentLesson { Student = student31, Lesson = lesson06 });
            StudentLessons.Add(new StudentLesson { Student = student32, Lesson = lesson07 });
            StudentLessons.Add(new StudentLesson { Student = student32, Lesson = lesson08 });
            StudentLessons.Add(new StudentLesson { Student = student33, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student33, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student34, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student34, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student35, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student35, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student36, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student36, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student37, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student37, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student38, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student38, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student39, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student39, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student40, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student40, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student41, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student41, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student42, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student42, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student43, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student43, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student44, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student44, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student45, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student45, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student46, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student46, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student47, Lesson = lesson09 });
            StudentLessons.Add(new StudentLesson { Student = student47, Lesson = lesson10 });
            StudentLessons.Add(new StudentLesson { Student = student48, Lesson = lesson11 });
            StudentLessons.Add(new StudentLesson { Student = student48, Lesson = lesson12 });
            StudentLessons.Add(new StudentLesson { Student = student49, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student49, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student50, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student50, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student51, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student51, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student52, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student52, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student53, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student53, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student54, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student54, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student55, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student55, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student56, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student56, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student57, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student57, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student58, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student58, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student59, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student59, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student60, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student60, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student61, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student61, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student62, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student62, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student63, Lesson = lesson13 });
            StudentLessons.Add(new StudentLesson { Student = student63, Lesson = lesson14 });
            StudentLessons.Add(new StudentLesson { Student = student64, Lesson = lesson15 });
            StudentLessons.Add(new StudentLesson { Student = student64, Lesson = lesson16 });
            StudentLessons.Add(new StudentLesson { Student = student65, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student65, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student66, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student66, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student67, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student67, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student68, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student68, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student69, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student69, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student70, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student70, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student71, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student71, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student72, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student72, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student73, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student73, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student74, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student74, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student75, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student75, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student76, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student76, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student77, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student77, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student78, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student78, Lesson = lesson20 });
            StudentLessons.Add(new StudentLesson { Student = student79, Lesson = lesson17 });
            StudentLessons.Add(new StudentLesson { Student = student79, Lesson = lesson18 });
            StudentLessons.Add(new StudentLesson { Student = student80, Lesson = lesson19 });
            StudentLessons.Add(new StudentLesson { Student = student80, Lesson = lesson20 });

            var contactInfo01 = new ContactInfo { Student = student01 };
            var contactInfo02 = new ContactInfo { Address = "1 Prince Dr. Hephzibah, GA 30815", Student = student02 };
            var contactInfo03 = new ContactInfo { Email = "john.jones@gmail.com", Student = student03 };
            //var contactInfo04 = new ContactInfo { Student = student04 };
            var contactInfo05 = new ContactInfo { Address = "221 South Homestead Ave. Anoka, MN 55303", Student = student05 };
            var contactInfo06 = new ContactInfo { Address = "71 Highland Dr. East Elmhurst, NY 11369", Email = "linda.miller@hotmail.com", Student = student06 };
            var contactInfo07 = new ContactInfo { Student = student07 };
            var contactInfo08 = new ContactInfo { Address = "62 La Sierra Rd. Odenton, MD 21113", Student = student08 };
            var contactInfo09 = new ContactInfo { Email = "mark.taylor@yahoo.com", Student = student09 };
            var contactInfo10 = new ContactInfo { Student = student10 };
            var contactInfo11 = new ContactInfo { Address = "9959 Penn Road La Porte, IN 46350", Student = student11 };
            var contactInfo12 = new ContactInfo { Address = "455 Green Hill St. Endicott, NY 13760", Email = "jennifer.jackson@gmail.com", Student = student12 };
            var contactInfo13 = new ContactInfo { Student = student13 };
            var contactInfo14 = new ContactInfo { Address = "99 W. Edgefield Street Southgate, MI 48195", Student = student14 };
            var contactInfo15 = new ContactInfo { Email = "charles.martin@hotmail.com", Student = student15 };
            //var contactInfo16 = new ContactInfo { Student = student16 };
            var contactInfo17 = new ContactInfo { Address = "9345 Arch Ave. Westmont, IL 60559", Student = student17 };
            var contactInfo18 = new ContactInfo { Address = "981 North Primrose St. Duarte, CA 91010", Email = "lisa.clark@yahoo.com", Student = student18 };
            var contactInfo19 = new ContactInfo { Student = student19 };
            var contactInfo20 = new ContactInfo { Address = "69 Oxford St. Marysville, OH 43040", Student = student20 };
            var contactInfo21 = new ContactInfo { Email = "christopher.walker@gmail.com", Student = student21 };
            var contactInfo22 = new ContactInfo { Student = student22 };
            var contactInfo23 = new ContactInfo { Address = "9354 Poplar St. Deland, FL 32720", Student = student23 };
            var contactInfo24 = new ContactInfo { Address = "10 Heritage Street Jonesborough, TN 37659", Email = "betty.young@hotmail.com", Student = student24 };
            var contactInfo25 = new ContactInfo { Student = student25 };
            var contactInfo26 = new ContactInfo { Address = "9656 Riverside Street Glen Ellyn, IL 60137", Student = student26 };
            var contactInfo27 = new ContactInfo { Email = "james.hill@yahoo.com", Student = student27 };
            //var contactInfo28 = new ContactInfo { Student = student28 };
            var contactInfo29 = new ContactInfo { Address = "323 Green Hill Court Palm Beach Gardens, FL 33410", Student = student29 };
            var contactInfo30 = new ContactInfo { Address = "7117 Saxton St. Ooltewah, TN 37363", Email = "donna.adams@gmail.com", Student = student30 };
            var contactInfo31 = new ContactInfo { Student = student31 };
            var contactInfo32 = new ContactInfo { Address = "70 East Jackson St. Long Branch, NJ 07740", Student = student32 };
            var contactInfo33 = new ContactInfo { Email = "thomas.jackson@hotmail.com", Student = student33 };
            var contactInfo34 = new ContactInfo { Student = student34 };
            var contactInfo35 = new ContactInfo { Address = "8396 Schoolhouse Ave. Collegeville, PA 19426", Student = student35 };
            var contactInfo36 = new ContactInfo { Address = "733 Leeton Ridge St. Lincoln Park, MI 48146", Email = "dorothy.hill@yahoo.com", Student = student36 };
            var contactInfo37 = new ContactInfo { Student = student37 };
            var contactInfo38 = new ContactInfo { Address = "1 Arcadia St. Thornton, CO 80241", Student = student38 };
            var contactInfo39 = new ContactInfo { Email = "james.carter@gmail.com", Student = student39 };
            //var contactInfo40 = new ContactInfo { Student = student40 };
            var contactInfo41 = new ContactInfo { Address = "614 West Rd. Wayne, NJ 07470", Student = student41 };
            var contactInfo42 = new ContactInfo { Address = "76 Lakeshore Ave. West Springfield, MA 01089", Email = "sandra.walker@hotmail.com", Student = student42 };
            var contactInfo43 = new ContactInfo { Student = student43 };
            var contactInfo44 = new ContactInfo { Address = "8512 Clinton Circle Cartersville, GA 30120", Student = student44 };
            var contactInfo45 = new ContactInfo { Email = "daniel.martin@yahoo.com", Student = student45 };
            var contactInfo46 = new ContactInfo { Student = student46 };
            var contactInfo47 = new ContactInfo { Address = "65 East St. Winter Springs, FL 32708", Student = student47 };
            var contactInfo48 = new ContactInfo { Address = "7 Hilldale St. Taunton, MA 02780", Email = "mary.lee@gmail.com", Student = student48 };
            var contactInfo49 = new ContactInfo { Student = student49 };
            var contactInfo50 = new ContactInfo { Address = "7869 Armstrong Court Vicksburg, MS 39180", Student = student50 };
            var contactInfo51 = new ContactInfo { Email = "james.lee@hotmail.com", Student = student51 };
            //var contactInfo52 = new ContactInfo { Student = student52 };
            var contactInfo53 = new ContactInfo { Address = "9952 Ann Lane Elizabeth City, NC 27909", Student = student53 };
            var contactInfo54 = new ContactInfo { Address = "157 Bayport Dr. Fullerton, CA 92831", Email = "lisa.jones@yahoo.com", Student = student54 };
            var contactInfo55 = new ContactInfo { Student = student55 };
            var contactInfo56 = new ContactInfo { Address = "7707 Meadowbrook Lane Montgomery, AL 36109", Student = student56 };
            var contactInfo57 = new ContactInfo { Email = "donald.miller@gmail.com", Student = student57 };
            var contactInfo58 = new ContactInfo { Student = student58 };
            var contactInfo59 = new ContactInfo { Address = "9353 East Eagle St. Lewiston, ME 04240", Student = student59 };
            var contactInfo60 = new ContactInfo { Address = "9866 Tailwater Circle Carrollton, GA 30117", Email = "patricia.clark@hotmail.com", Student = student60 };
            var contactInfo61 = new ContactInfo { Student = student61 };
            var contactInfo62 = new ContactInfo { Address = "20 Oxford Lane Potomac, MD 20854", Student = student62 };
            var contactInfo63 = new ContactInfo { Email = "john.smith@yahoo.com", Student = student63 };
            //var contactInfo64 = new ContactInfo { Student = student64 };
            var contactInfo65 = new ContactInfo { Address = "651 Garden Circle Naples, FL 34116", Student = student65 };
            var contactInfo66 = new ContactInfo { Address = "559 Harrison Lane Bel Air, MD 21014", Email = "sandra.king@gmail.com", Student = student66 };
            var contactInfo67 = new ContactInfo { Student = student67 };
            var contactInfo68 = new ContactInfo { Address = "9805 Front St. Glen Ellyn, IL 60137", Student = student68 };
            var contactInfo69 = new ContactInfo { Email = "michael.lee@hotmail.com", Student = student69 };
            var contactInfo70 = new ContactInfo { Student = student70 };
            var contactInfo71 = new ContactInfo { Address = "31 South Constitution Street Nicholasville, KY 40356", Student = student71 };
            var contactInfo72 = new ContactInfo { Address = "58 Grant Lane Florence, SC 29501", Email = "dorothy.carter@yahoo.com", Student = student72 };
            var contactInfo73 = new ContactInfo { Student = student73 };
            var contactInfo74 = new ContactInfo { Address = "5 Addison Street Downers Grove, IL 60515", Student = student74 };
            var contactInfo75 = new ContactInfo { Email = "james.moore@gmail.com", Student = student75 };
            //var contactInfo76 = new ContactInfo { Student = student76 };
            var contactInfo77 = new ContactInfo { Address = "8987 1st Ave. Lowell, MA 01851", Student = student77 };
            var contactInfo78 = new ContactInfo { Address = "20 Myrtle Street Woodstock, GA 30188", Email = "susan.robinson@hotmail.com", Student = student78 };
            var contactInfo79 = new ContactInfo { Student = student79 };
            var contactInfo80 = new ContactInfo { Address = "886B West Pacific Ave. Chardon, OH 44024", Student = student80 };

            ContactInfo.Add(contactInfo01);
            ContactInfo.Add(contactInfo02);
            ContactInfo.Add(contactInfo03);
            //ContactInfo.Add(contactInfo04);
            ContactInfo.Add(contactInfo05);
            ContactInfo.Add(contactInfo06);
            ContactInfo.Add(contactInfo07);
            ContactInfo.Add(contactInfo08);
            ContactInfo.Add(contactInfo09);
            ContactInfo.Add(contactInfo10);
            ContactInfo.Add(contactInfo11);
            ContactInfo.Add(contactInfo12);
            ContactInfo.Add(contactInfo13);
            ContactInfo.Add(contactInfo14);
            ContactInfo.Add(contactInfo15);
            //ContactInfo.Add(contactInfo16);
            ContactInfo.Add(contactInfo17);
            ContactInfo.Add(contactInfo18);
            ContactInfo.Add(contactInfo19);
            ContactInfo.Add(contactInfo20);
            ContactInfo.Add(contactInfo21);
            ContactInfo.Add(contactInfo22);
            ContactInfo.Add(contactInfo23);
            ContactInfo.Add(contactInfo24);
            ContactInfo.Add(contactInfo25);
            ContactInfo.Add(contactInfo26);
            ContactInfo.Add(contactInfo27);
            //ContactInfo.Add(contactInfo28);
            ContactInfo.Add(contactInfo29);
            ContactInfo.Add(contactInfo30);
            ContactInfo.Add(contactInfo31);
            ContactInfo.Add(contactInfo32);
            ContactInfo.Add(contactInfo33);
            ContactInfo.Add(contactInfo34);
            ContactInfo.Add(contactInfo35);
            ContactInfo.Add(contactInfo36);
            ContactInfo.Add(contactInfo37);
            ContactInfo.Add(contactInfo38);
            ContactInfo.Add(contactInfo39);
            //ContactInfo.Add(contactInfo40);
            ContactInfo.Add(contactInfo41);
            ContactInfo.Add(contactInfo42);
            ContactInfo.Add(contactInfo43);
            ContactInfo.Add(contactInfo44);
            ContactInfo.Add(contactInfo45);
            ContactInfo.Add(contactInfo46);
            ContactInfo.Add(contactInfo47);
            ContactInfo.Add(contactInfo48);
            ContactInfo.Add(contactInfo49);
            ContactInfo.Add(contactInfo50);
            ContactInfo.Add(contactInfo51);
            //ContactInfo.Add(contactInfo52);
            ContactInfo.Add(contactInfo53);
            ContactInfo.Add(contactInfo54);
            ContactInfo.Add(contactInfo55);
            ContactInfo.Add(contactInfo56);
            ContactInfo.Add(contactInfo57);
            ContactInfo.Add(contactInfo58);
            ContactInfo.Add(contactInfo59);
            ContactInfo.Add(contactInfo60);
            ContactInfo.Add(contactInfo61);
            ContactInfo.Add(contactInfo62);
            ContactInfo.Add(contactInfo63);
            //ContactInfo.Add(contactInfo64);
            ContactInfo.Add(contactInfo65);
            ContactInfo.Add(contactInfo66);
            ContactInfo.Add(contactInfo67);
            ContactInfo.Add(contactInfo68);
            ContactInfo.Add(contactInfo69);
            ContactInfo.Add(contactInfo70);
            ContactInfo.Add(contactInfo71);
            ContactInfo.Add(contactInfo72);
            ContactInfo.Add(contactInfo73);
            ContactInfo.Add(contactInfo74);
            ContactInfo.Add(contactInfo75);
            //ContactInfo.Add(contactInfo76);
            ContactInfo.Add(contactInfo77);
            ContactInfo.Add(contactInfo78);
            ContactInfo.Add(contactInfo79);
            ContactInfo.Add(contactInfo80);

            Phones.Add(new Phone { Number = "512-555-0196", ContactInfo = contactInfo01 });
            Phones.Add(new Phone { Number = "860-555-0188", ContactInfo = contactInfo01 });
            Phones.Add(new Phone { Number = "302-555-0162", ContactInfo = contactInfo02 });
            Phones.Add(new Phone { Number = "307-555-0142", ContactInfo = contactInfo03 });
            Phones.Add(new Phone { Number = "916-555-0154", ContactInfo = contactInfo03 });
            //Phones.Add(new Phone { Number = "307-555-0172", ContactInfo = contactInfo04 });
            Phones.Add(new Phone { Number = "608-555-0165", ContactInfo = contactInfo05 });
            Phones.Add(new Phone { Number = "512-555-0181", ContactInfo = contactInfo05 });
            //Phones.Add(new Phone { Number = "307-555-0144", ContactInfo = contactInfo06 });
            Phones.Add(new Phone { Number = "302-555-0147", ContactInfo = contactInfo07 });
            Phones.Add(new Phone { Number = "608-555-0139", ContactInfo = contactInfo07 });
            Phones.Add(new Phone { Number = "614-555-0176", ContactInfo = contactInfo08 });
            Phones.Add(new Phone { Number = "860-555-0130", ContactInfo = contactInfo09 });
            Phones.Add(new Phone { Number = "401-555-0168", ContactInfo = contactInfo09 });
            Phones.Add(new Phone { Number = "307-555-0146", ContactInfo = contactInfo10 });
            Phones.Add(new Phone { Number = "916-555-0109", ContactInfo = contactInfo11 });
            Phones.Add(new Phone { Number = "302-555-0135", ContactInfo = contactInfo11 });
            Phones.Add(new Phone { Number = "512-555-0176", ContactInfo = contactInfo12 });
            Phones.Add(new Phone { Number = "614-555-0156", ContactInfo = contactInfo13 });
            Phones.Add(new Phone { Number = "401-555-0183", ContactInfo = contactInfo13 });
            Phones.Add(new Phone { Number = "608-555-0122", ContactInfo = contactInfo14 });
            Phones.Add(new Phone { Number = "307-555-0184", ContactInfo = contactInfo15 });
            Phones.Add(new Phone { Number = "608-555-0174", ContactInfo = contactInfo15 });
            //Phones.Add(new Phone { Number = "608-555-0187", ContactInfo = contactInfo16 });
            Phones.Add(new Phone { Number = "860-555-0183", ContactInfo = contactInfo17 });
            Phones.Add(new Phone { Number = "401-555-0186", ContactInfo = contactInfo17 });
            //Phones.Add(new Phone { Number = "302-555-0136", ContactInfo = contactInfo18 });
            Phones.Add(new Phone { Number = "916-555-0150", ContactInfo = contactInfo19 });
            Phones.Add(new Phone { Number = "302-555-0167", ContactInfo = contactInfo19 });
            Phones.Add(new Phone { Number = "614-555-0175", ContactInfo = contactInfo20 });
            Phones.Add(new Phone { Number = "785-555-0167", ContactInfo = contactInfo21 });
            Phones.Add(new Phone { Number = "503-555-0128", ContactInfo = contactInfo21 });
            Phones.Add(new Phone { Number = "651-555-0143", ContactInfo = contactInfo22 });
            Phones.Add(new Phone { Number = "405-555-0183", ContactInfo = contactInfo23 });
            Phones.Add(new Phone { Number = "334-555-0157", ContactInfo = contactInfo23 });
            Phones.Add(new Phone { Number = "405-555-0176", ContactInfo = contactInfo24 });
            Phones.Add(new Phone { Number = "651-555-0163", ContactInfo = contactInfo25 });
            Phones.Add(new Phone { Number = "202-555-0186", ContactInfo = contactInfo25 });
            Phones.Add(new Phone { Number = "405-555-0110", ContactInfo = contactInfo26 });
            Phones.Add(new Phone { Number = "651-555-0114", ContactInfo = contactInfo27 });
            Phones.Add(new Phone { Number = "785-555-0113", ContactInfo = contactInfo27 });
            //Phones.Add(new Phone { Number = "503-555-0178", ContactInfo = contactInfo28 });
            Phones.Add(new Phone { Number = "334-555-0125", ContactInfo = contactInfo29 });
            Phones.Add(new Phone { Number = "202-555-0143", ContactInfo = contactInfo29 });
            //Phones.Add(new Phone { Number = "334-555-0177", ContactInfo = contactInfo30 });
            Phones.Add(new Phone { Number = "518-555-0130", ContactInfo = contactInfo31 });
            Phones.Add(new Phone { Number = "518-555-0188", ContactInfo = contactInfo31 });
            Phones.Add(new Phone { Number = "701-555-0115", ContactInfo = contactInfo32 });
            Phones.Add(new Phone { Number = "303-555-0101", ContactInfo = contactInfo33 });
            Phones.Add(new Phone { Number = "303-555-9967", ContactInfo = contactInfo33 });
            Phones.Add(new Phone { Number = "402-555-0180", ContactInfo = contactInfo34 });
            Phones.Add(new Phone { Number = "701-555-0163", ContactInfo = contactInfo35 });
            Phones.Add(new Phone { Number = "701-555-7878", ContactInfo = contactInfo35 });
            Phones.Add(new Phone { Number = "518-555-0155", ContactInfo = contactInfo36 });
            Phones.Add(new Phone { Number = "303-555-0149", ContactInfo = contactInfo37 });
            Phones.Add(new Phone { Number = "303-555-3344", ContactInfo = contactInfo37 });
            Phones.Add(new Phone { Number = "808-555-0197", ContactInfo = contactInfo38 });
            Phones.Add(new Phone { Number = "919-555-0115", ContactInfo = contactInfo39 });
            Phones.Add(new Phone { Number = "919-555-0101", ContactInfo = contactInfo39 });
            //Phones.Add(new Phone { Number = "919-555-0147", ContactInfo = contactInfo40 });
            Phones.Add(new Phone { Number = "402-555-0144", ContactInfo = contactInfo41 });
            Phones.Add(new Phone { Number = "402-555-0155", ContactInfo = contactInfo41 });
            //Phones.Add(new Phone { Number = "808-555-0146", ContactInfo = contactInfo42 });
            Phones.Add(new Phone { Number = "919-555-0142", ContactInfo = contactInfo43 });
            Phones.Add(new Phone { Number = "919-555-3232", ContactInfo = contactInfo43 });
            Phones.Add(new Phone { Number = "808-555-0147", ContactInfo = contactInfo44 });
            Phones.Add(new Phone { Number = "518-555-0145", ContactInfo = contactInfo45 });
            Phones.Add(new Phone { Number = "518-555-0167", ContactInfo = contactInfo45 });
            Phones.Add(new Phone { Number = "402-555-0123", ContactInfo = contactInfo46 });
            Phones.Add(new Phone { Number = "303-555-0118", ContactInfo = contactInfo47 });
            Phones.Add(new Phone { Number = "303-555-0199", ContactInfo = contactInfo47 });
            Phones.Add(new Phone { Number = "701-555-0185", ContactInfo = contactInfo48 });
            Phones.Add(new Phone { Number = "417-555-0158", ContactInfo = contactInfo49 });
            Phones.Add(new Phone { Number = "843-555-0139", ContactInfo = contactInfo49 });
            Phones.Add(new Phone { Number = "505-555-0154", ContactInfo = contactInfo50 });
            Phones.Add(new Phone { Number = "804-555-0127", ContactInfo = contactInfo51 });
            Phones.Add(new Phone { Number = "225-555-0174", ContactInfo = contactInfo51 });
            //Phones.Add(new Phone { Number = "225-555-0101", ContactInfo = contactInfo52 });
            Phones.Add(new Phone { Number = "385-555-0137", ContactInfo = contactInfo53 });
            Phones.Add(new Phone { Number = "417-555-0190", ContactInfo = contactInfo53 });
            //Phones.Add(new Phone { Number = "843-555-0184", ContactInfo = contactInfo54 });
            Phones.Add(new Phone { Number = "609-555-0177", ContactInfo = contactInfo55 });
            Phones.Add(new Phone { Number = "225-555-0134", ContactInfo = contactInfo55 });
            Phones.Add(new Phone { Number = "385-555-0167", ContactInfo = contactInfo56 });
            Phones.Add(new Phone { Number = "406-555-0143", ContactInfo = contactInfo57 });
            Phones.Add(new Phone { Number = "850-555-0167", ContactInfo = contactInfo57 });
            Phones.Add(new Phone { Number = "406-555-0188", ContactInfo = contactInfo58 });
            Phones.Add(new Phone { Number = "406-555-0162", ContactInfo = contactInfo59 });
            Phones.Add(new Phone { Number = "505-555-0152", ContactInfo = contactInfo59 });
            Phones.Add(new Phone { Number = "225-555-0138", ContactInfo = contactInfo60 });
            Phones.Add(new Phone { Number = "609-555-0155", ContactInfo = contactInfo61 });
            Phones.Add(new Phone { Number = "804-555-0170", ContactInfo = contactInfo61 });
            Phones.Add(new Phone { Number = "843-555-0124", ContactInfo = contactInfo62 });
            Phones.Add(new Phone { Number = "804-555-0175", ContactInfo = contactInfo63 });
            Phones.Add(new Phone { Number = "385-555-0139", ContactInfo = contactInfo63 });
            //Phones.Add(new Phone { Number = "850-555-0152", ContactInfo = contactInfo64 });
            Phones.Add(new Phone { Number = "385-555-0169", ContactInfo = contactInfo65 });
            Phones.Add(new Phone { Number = "505-555-0123", ContactInfo = contactInfo65 });
            //Phones.Add(new Phone { Number = "609-555-0182", ContactInfo = contactInfo66 });
            Phones.Add(new Phone { Number = "804-555-0182", ContactInfo = contactInfo67 });
            Phones.Add(new Phone { Number = "843-555-0196", ContactInfo = contactInfo67 });
            Phones.Add(new Phone { Number = "417-555-0135", ContactInfo = contactInfo68 });
            Phones.Add(new Phone { Number = "843-555-0157", ContactInfo = contactInfo69 });
            Phones.Add(new Phone { Number = "505-555-0102", ContactInfo = contactInfo69 });
            Phones.Add(new Phone { Number = "850-555-0102", ContactInfo = contactInfo70 });
            Phones.Add(new Phone { Number = "417-555-0130", ContactInfo = contactInfo71 });
            Phones.Add(new Phone { Number = "609-555-0163", ContactInfo = contactInfo71 });
            Phones.Add(new Phone { Number = "850-555-0199", ContactInfo = contactInfo72 });
            Phones.Add(new Phone { Number = "804-555-0142", ContactInfo = contactInfo73 });
            Phones.Add(new Phone { Number = "505-555-0116", ContactInfo = contactInfo73 });
            Phones.Add(new Phone { Number = "417-555-0110", ContactInfo = contactInfo74 });
            Phones.Add(new Phone { Number = "843-555-0143", ContactInfo = contactInfo75 });
            Phones.Add(new Phone { Number = "385-555-0165", ContactInfo = contactInfo75 });
            //Phones.Add(new Phone { Number = "850-555-0103", ContactInfo = contactInfo76 });
            Phones.Add(new Phone { Number = "417-555-0139", ContactInfo = contactInfo77 });
            Phones.Add(new Phone { Number = "609-555-0136", ContactInfo = contactInfo77 });
            //Phones.Add(new Phone { Number = "850-555-0189", ContactInfo = contactInfo78 });
            Phones.Add(new Phone { Number = "804-555-0179", ContactInfo = contactInfo79 });
            Phones.Add(new Phone { Number = "385-555-0115", ContactInfo = contactInfo79 });
            Phones.Add(new Phone { Number = "609-555-0146", ContactInfo = contactInfo80 });

            var logEvent1 = new LogEvent { Name = nameof(ArgumentNullException) };
            var logEvent2 = new LogEvent { Name = nameof(IndexOutOfRangeException) };
            var logEvent3 = new LogEvent { Name = nameof(AccessViolationException) };

            LogEvents.Add(logEvent1);
            LogEvents.Add(logEvent2);
            LogEvents.Add(logEvent3);

            LogDetail.Add(new LogDetail { LogDate = new DateTime(2018, 3, 3, 4, 24, 33), Text = "Object reference not set to an instance of an object.", LogEvent = logEvent1 });
            LogDetail.Add(new LogDetail { LogDate = new DateTime(2018, 4, 5, 14, 20, 15), Text = "Index was out of range. Must be non-negative and less than the size of the collection.", LogEvent = logEvent2 });
            LogDetail.Add(new LogDetail { LogDate = new DateTime(2018, 11, 12, 16, 55, 20), Text = "Access is denied.", LogEvent = logEvent3 });

            SystemInfo.Add(new SystemInfo { OS = "WINDOWS", OSVersion = "10", LogEvent = logEvent1 });
            SystemInfo.Add(new SystemInfo { OS = "UBUNTU", OSVersion = "16.04 LTS", LogEvent = logEvent2 });
            SystemInfo.Add(new SystemInfo { OS = "MAC OS X", OSVersion = "10.1", LogEvent = logEvent3 });
        }
    }
}
